spring:
  redis:
    redisson:
      config: |
        sentinelServersConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          failedSlaveReconnectionInterval: 3000
          failedSlaveNodeDetector: !<org.redisson.client.FailedConnectionDetector> {}
          subscriptionsPerConnection: 5
          clientName: null
          loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          slaveConnectionMinimumIdleSize: 24
          slaveConnectionPoolSize: 64
          masterConnectionMinimumIdleSize: 24
          masterConnectionPoolSize: 64
          readMode: "SLAVE"
          subscriptionMode: "SLAVE"
          sentinelAddresses:
          - "redis://redis-sentinel1:26379"
          - "redis://redis-sentinel2:26379"
          - "redis://redis-sentinel3:26379"
          masterName: "mymaster"
          password: masterpassword
          sentinelPassword: sentinelpassword
          database: 0
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.Kryo5Codec> {}
        transportMode: "NIO"
