version: "3"
name: 'redis-1m-3s'
services:
  redis-master:
    container_name: redis-master
    image: redis-master
    volumes:
      - redis-master-conf:/etc/redis
      - redis-master-data:/data
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6379:6379
    networks:
      - private
    command: --requirepass ${REDIS_PASSWORD}
  redis-slave:
    container_name: redis-slave
    image: redis-slave
    volumes:
      - redis-slave-conf:/etc/redis
      - redis-slave-data:/data
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6378:6379
    networks:
      - private
    depends_on:
      - redis-master
    command: --requirepass ${REDIS_PASSWORD} --replicaof redis-master 6379 --masterauth ${REDIS_PASSWORD}
  redis-slave1:
    container_name: redis-slave1
    image: redis-slave
    volumes:
      - redis-slave1-conf:/etc/redis
      - redis-slave1-data:/data
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6377:6379
    networks:
      - private
    depends_on:
      - redis-master
    command: --requirepass ${REDIS_PASSWORD} --replicaof redis-master 6379 --masterauth ${REDIS_PASSWORD}
  redis-slave2:
    container_name: redis-slave2
    image: redis-slave
    volumes:
      - redis-slave2-conf:/etc/redis
      - redis-slave2-data:/data
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6376:6379
    networks:
      - private
    depends_on:
      - redis-master
    command: --requirepass ${REDIS_PASSWORD} --replicaof redis-master 6379 --masterauth ${REDIS_PASSWORD}
# 将配置文件挂载到docker的容器卷中管理
volumes:
  redis-master-conf:
  redis-slave-conf:
  redis-slave1-conf:
  redis-slave2-conf:
  redis-master-data:
  redis-slave-data:
  redis-slave1-data:
  redis-slave2-data:
# 创建网络让容器之间可以互相访问
networks:
  private: